### ISSUE TITLE
示例能有对应的中文翻译或图片就好了

### ISSUE THREAD

**Issue by iactor** [HuasoFoundries/jpgraph#70]
示例能有对应的中文翻译或图片就好了

**Comment by peter279k** [comment]
To be international, please describe your issue and title.

Thanks.

**Comment by ffflabs** [comment]
Uh, Google Translate didn't help much either

**Comment by peter279k** [comment]
@ffflabs, I guess he wants the every sample has the Chinese introduction.

**Comment by ffflabs** [comment]
Hmm I wouldn't  know how am I supposed to translate the examples, and it doesn't make sense to transliterate to chinese characters while preserving english. I'd make a fool of myself :smile: 

However, perhaps this issue is meant to address the usage of chinese fonts and not the language itself.

First and foremost: fonts such as `simsun.ttc` and `bkai00mp.ttf` are **HUGE** and I cannot add 15M of statics just for the sake of an example. BUT, I made a working example:

![image](https://user-images.githubusercontent.com/238439/71895333-869ecf00-312f-11ea-89e9-d47b16173c5d.png)

https://github.com/HuasoFoundries/jpgraph/blob/master/Examples/examples_multigraph/example_two_graphs_chinese.php#L20-L29


You just need to gunzip these fonts to  `src/fonts/`

[bkai00mp.ttf.gz](https://github.com/HuasoFoundries/jpgraph/files/4030248/bkai00mp.ttf.gz)
[simsun.ttc.gz](https://github.com/HuasoFoundries/jpgraph/files/4030250/simsun.ttc.gz)


Caveat: _bkai00mp_ works fine. _simsun_ only works if you set it as "user defined font" (see above). If you set it as `FF_SIMSUN` (which would make much more sense...) there's a hardcoded encoding conversion that breaks stuff.
